# Cache node modules - speeds up future builds
cache:
  paths:
    - node_modules
stages:
  - build
  - deploy

variables:
  S3_BUCKET_DEV: ${BUCKET_DEV}
  S3_BUCKET_PROD: ${BUCKET_PROD}

# Build section
#---------------
.yarn_build:
  image: node:latest
  script: |
    pwd
    cd /builds/ctd/proyecto-integrador-1022/0521-pt-c1/grupo-05/front_pigrupo5/digital-booking
    yarn # Install all dependencies
    yarn build # Build command
  artifacts:
    paths:
      - ./build
      
yarn_dev:
  extends: .yarn_build
  stage: build
  before_script:
    - export APP_ENV="dev"
  only:
    refs:
      - Develop_FrontEnd

yarn_prod:
  extends: .yarn_build
  stage: build
  before_script:
    - export APP_ENV="prod"
  only:
    refs:
      - Main_Frontend

# Deploy section
#---------------
.deploy_aws:
  image: python:latest
  when: manual
  script: |
    pip install awscli #Install awscli tools
    aws s3 sync ./build/ s3://${S3_BUCKET}

deploy_dev:
  extends: .deploy_aws
  stage: deploy
  dependencies:
    - yarn_dev
  before_script:
    - export S3_BUCKET=${S3_BUCKET_DEV}
  only:
    refs:
      - Develop_FrontEnd

deploy_prod:
  extends: .deploy_aws
  stage: deploy
  dependencies:
    - yarn_prod
  before_script:
    - export S3_BUCKET=${S3_BUCKET_PROD}
  only:
    refs:
      - Main_Frontend