stages:  
  - build
  - deploy  

Build App:  
  stage: build
  image: maven:3.8.5-openjdk-17-slim
  script:
    - echo "Building app..."
    - mvn clean
    - mvn package -B
    - ls target
    - echo "Finished building the app"
  artifacts:
    paths:      
      - target/*.jar
  only:
      - Main_Backend

Deploy App:     
  image: alpine:3.11       
  stage: deploy                                                                                                                       
  before_script:                                                                                                                                
    - sudo apt-get update -qq && sudo apt-get install -y -qq sshpass                                                                                                                                                                                                                      
  script:   
    - echo "Init Deploy App"                                                                                                                                    
    - sshpass -V                                                                                                                                
    - export SSHPASS=$CI_USER_PASS                                                                                                              
    - sshpass -e scp -o StrictHostKeyChecking=no target/*.jar gitlab-ci@"$EC2_IPADDRESS":/home/gitlab-ci                            
    - sshpass -e ssh -tt -o StrictHostKeyChecking=no gitlab-ci@"$EC2_IPADDRESS" sudo mv /home/gitlab-ci/*.jar /opt/java/webapps     
    - sshpass -e ssh -tt -o StrictHostKeyChecking=no gitlab-ci@"$EC2_IPADDRESS" sudo systemctl restart gitlab-ci-demo.service
  only:
      - Main_Backend