stages:  
  - build
  - deploy  

Build App:  
  stage: build
  image: maven:3.8.5-openjdk-17-slim
  script:
    - echo "Building app..."
    - mvn clean
    - mvn package -B
    - ls target
    - echo "Finished building the app"
  artifacts:
    paths:      
      - target/*.jar
  only:
      - Main_Backend

Deploy App:     
  image: alpine:3.11       
  stage: deploy                                                                                                                       
  before_script:                                                                                                                                
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'   
    - eval $(ssh-agent -s)  
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -  
    - mkdir -p ~/.ssh  
    - chmod 700 ~/.ssh  
    - ssh-keyscan $EC2_IPADDRESS >> ~/.ssh/known_hosts  
    - chmod 644 ~/.ssh/known_hosts                                                                                                                                                                                                                        
  script:   
    - echo "Init Deploy App"                                                                                                                                    
    - ssh "$SSH_USER"@"$EC2_IPADDRESS" "sudo systemctl stop dhGrupo5.service"  
    - scp -o StrictHostKeyChecking=no ./target/*jar "$SSH_USER"@"$EC2_IPADDRESS":~
    - ssh "$SSH_USER"@"$EC2_IPADDRESS" "ls -lr"
    - ssh "$SSH_USER"@"$EC2_IPADDRESS" "sudo systemctl start dhGrupo5.service"

  only:
      - Main_Backend